min_fastlane_version("2.71.0")

default_platform(:ios)

platform :ios do
    xcversion(version: "~> 11.4.0")

    # Load local enviroment variables
    if File.exist?('.env')
        open('.env', 'r').readlines.each do |l|
            kv = l.split('=')
            ENV[kv[0]] = kv[1].chomp
        end
    end

    desc "To publish app you need to specify APP_CENTER_API_TOKEN in your enviroment (.env file in project source root)."

    lane :beta_appcenter do |options|
        ensure_git_status_clean
        ensure_git_branch(branch: 'dev')

        build_ios_app(
            output_directory: "build/",
            build_path: "build/",
            derived_data_path: "build/DerivedData/",
            scheme: "Example",
            export_method: "ad-hoc",
            skip_profile_detection: true,
            export_options: {
                uploadSymbols: true,
                provisioningProfiles: {
                    "com.redmadrobot.spb.robologs.testApplication" => "Robologs Test Application Distribution"
                }
            },
            clean: true,
            output_directory: "build"
        )

        appcenter_upload(
            api_token: ENV["APP_CENTER_API_TOKEN"],
            owner_name: "Redmadrobot-SPb",
            app_name: "Robologs-Demonstration",
            destinations: "Internal",
            destination_type: "group",
            notify_testers: true
        )
    end
end
