min_fastlane_version("2.71.0")

default_platform(:ios)

platform :ios do
    # Load local enviroment variables
    if File.exist?('.env')
        open('.env', 'r').readlines.each do |l|
            kv = l.split('=')
            ENV[kv[0]] = kv[1].chomp
        end
    end

    desc "Bump build and publish Robologs Test App to App Center."
    desc "To publish app you need to specify APP_CENTER_API_TOKEN in your enviroment."
    desc "API token is generated in https://appcenter.ms/settings/apitokens with full access."
    desc "*Usage:* `fastlane publish_test_app [bump_version:true]`"
    desc "*Parameters:*"
    desc "  - bump_version: true/false. If true fastlane will also bump version, default: false."
    lane :publish_test_app do |options|
        ensure_git_status_clean
        ensure_git_branch(branch: 'dev')

        release_notes = prompt(
            text: "Release notes: ",
            multi_line_end_keyword: "END"
        )

        if options[:bump_version]
            bump_version(target: "Example")
        end
        increment_build_number

        build(
            scheme: "Example",
            export_method: "ad-hoc",
            export_options: {
                provisioningProfiles: {
                    "com.redmadrobot.spb.robologs.testApplication" => "Robologs Test Application Distribution"
                }
            }
        )

        example_version = current_version(target: "Example")

        upload_to_app_center(
            app_name: "Robologs-Demonstration", 
            release_notes: release_notes
        )
        commit_version_bump(
            message: "Build #{example_version}",
            xcodeproj: "Robologs.xcodeproj"
        )
        add_git_tag(tag: "v#{example_version}")
        push_to_git_remote(tags: true)
    end

    desc "Bump minor part of version (example 0.1.4 -> 0.1.5)."
    desc "*Usage:* `fastlane bump_version target:<TARGET>`"
    desc "*Parameters:*"
    desc "  - target - xcodeproj target to bump. Available targets:"
    desc "  -- Example - Robologs Test App"
    desc "  -- Robologs - Robologs SDK"
    lane :bump_version do |options|
        version = get_version_number(target: options[:target])
        list = version.split(".")
        incremented = String(Integer(list.last) + 1)
        new_version = "#{list.first}.#{incremented}"
        increment_version_number(version_number: new_version)
        increment_build_number(build_number: "0")
    end

    private_lane :current_version do |options|
        version_number = get_version_number(target: options[:target])
        build_number = build_number = get_build_number
        "#{version_number}(#{build_number})"
    end

    private_lane :build do |options|
        scheme = options[:scheme]
        output_name = options[:output_name]
        export_method = options[:export_method]
        export_options = options[:export_options]
        clean = options[:clean]

        update_version

        build_ios_app(
            scheme: scheme,
            output_directory: "build/",
            build_path: "build/",
            derived_data_path: "build/DerivedData/",
            output_name: output_name,
            include_symbols: true,
            export_method: export_method,
            export_options: export_options,
            clean: clean.nil? ? true : clean
        )
    end

    private_lane :update_version do
        increment_version_number(version_number: ENV["VERSION_NUMBER"]) if ENV["VERSION_NUMBER"]
        increment_build_number(build_number: ENV["BUILD_NUMBER"]) if ENV["BUILD_NUMBER"]
    end

    private_lane :upload_to_app_center do |options|
        api_token = ENV["APP_CENTER_API_TOKEN"]

        appcenter_upload(
            api_token: api_token,
            owner_name: "Redmadrobot-SPb",
            app_name: options[:app_name],
            destinations: "Internal",
            destination_type: "group",
            notify_testers: true,
            release_notes: options[:release_notes]
        )
    end
end
